FROM openjdk:25-jdk-slim-bookworm

RUN apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates
RUN cd /usr/share/ca-certificates && mkdir mylocal && cp -p /etc/ca-certificates.conf /etc/ca-certificates.conf.bak

COPY ./certs/__DOMAIN_NAME__.ca.crt  /certs/__DOMAIN_NAME__.ca.crt
RUN cd /usr/share/ca-certificates && cp /certs/__DOMAIN_NAME__.ca.crt mylocal/
RUN echo "mylocal/__DOMAIN_NAME__.ca.crt" >> /etc/ca-certificates.conf
RUN update-ca-certificates

RUN apt-get update && apt-get install -y less vim zip maven git wget curl

RUN git clone https://github.com/keycloak/keycloak-quickstarts.git && \
    wget https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-cli/3.4.3/spring-boot-cli-3.4.3-bin.tar.gz && \
    tar xzvf spring-boot-cli-3.4.3-bin.tar.gz 
ENV PATH=$PATH:/spring-3.4.3/bin/
ENV SPRING_HOME=/spring-3.4.3/
RUN cd /keycloak-quickstarts/ && mvn clean install && cd misc && mvn clean install 
WORKDIR /keycloak-quickstarts/spring/rest-authz-resource-server/


#CMD ["bash"]
CMD ["mvn","spring-boot:run"]
