services:
  rdl-flask-frontend-test-web-service-nginx:
    container_name: rdl-flask-frontend-test-web-service-nginx
    hostname: rdl-flask-frontend-test-web-service-nginx
    image: nginx:stable-perl
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/${DOMAIN_NAME}.crt:/opt/certs/${DOMAIN_NAME}.crt:ro
      - ./certs/${DOMAIN_NAME}.key:/opt/certs/${DOMAIN_NAME}.key:ro
    ports:
      - ${WEBAPP_FLASK_FRONTEND_PORT}:443
    networks:
      rdl-flask-frontend-test-web-service-network:
        ipv4_address: 172.20.0.42
    restart: always
  rdl-flask-frontend-test-web-service:
    container_name: rdl-flask-frontend-test-web-service
    hostname: rdl-flask-frontend-test-web-service
    build: .
    environment:
      - TZ=Asia/Tokyo
    networks:
      rdl-flask-frontend-test-web-service-network:
        ipv4_address: 172.20.0.43
    tty: true
    user: root
    restart: always
networks:
  rdl-flask-frontend-test-web-service-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.40/29
        gateway: 172.20.0.41
