services:
  rdl-pgsql:
    image: postgres:latest
    container_name: rdl-pgsql
    hostname: gpsql
    ports:
      - 5432:5432
    networks:
      rdl-pgsql-network:
        ipv4_address: 172.20.5.101
    volumes:
      - rdl-pgsql-store:/var/lib/postgresql/data
      - ./certs/${DOMAIN_NAME}.crt:/var/lib/postgresql/${DOMAIN_NAME}.crt:ro
      - ./certs/${DOMAIN_NAME}.key:/var/lib/postgresql/${DOMAIN_NAME}.key:ro
    tty: true
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/${DOMAIN_NAME}.crt -c ssl_key_file=/var/lib/postgresql/${DOMAIN_NAME}.key

  rdl-adminer-nginx:
    container_name: rdl-adminer-nginx
    hostname: rdl-adminer-nginx
    image: nginx:stable-perl
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../certs/${DOMAIN_NAME}.crt:/opt/certs/${DOMAIN_NAME}.crt:ro
      - ../../certs/${DOMAIN_NAME}.key:/opt/certs/${DOMAIN_NAME}.key:ro
    ports:
      - 8445:443
    networks:
      rdl-pgsql-network:
        ipv4_address: 172.20.5.100
        
  rdl-adminer:
    container_name: rdl-adminer
    hostname: rdl-adminer
    image: adminer
    restart: always
    networks:
      rdl-pgsql-network:
        ipv4_address: 172.20.5.102

networks:
  rdl-pgsql-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.5.0/24
        gateway: 172.20.5.1
volumes:
  rdl-pgsql-store:
