services:
  spark-kafka-receiver:
    container_name: spark-kafka-receiver
    hostname: spark-kafka-receiver
    build: .
    tty: true
    volumes:
      - ./data/:/home/spark/data/:ro
      - ./py/:/home/spark/py/:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TZ=Asia/Tokyo
    networks:
      spark-kafka-receiver-network:
        ipv4_address: 172.20.0.74
    restart: always
networks:
  spark-kafka-receiver-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.72/29
        gateway: 172.20.0.73
