services:
  spark-kafka-transmitter:
    container_name: spark-kafka-transmitter
    hostname: spark-kafka-transmitter
    build: .
    tty: true
    volumes:
      - ./conf/spark-defaults.conf:/opt/spark-3.5.5-bin-hadoop3-scala2.13/conf/spark-defaults.conf:ro
      - ./data/:/home/spark/data/:ro
      - ./py/:/home/spark/py/:ro
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_ENDPOINT=${DOMAIN_NAME}:9000
      - AWS_REGION=us-east-1
      - DOMAIN_NAME=${DOMAIN_NAME}
      - TZ=Asia/Tokyo
    networks:
      spark-kafka-transmitter-network:
        ipv4_address: 172.20.0.66
    restart: always
networks:
  spark-kafka-transmitter-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.64/29
        gateway: 172.20.0.65
