services:
  rdl-lam-nginx:
    container_name: rdl-lam-nginx
    hostname: rdl-lam-nginx
    image: nginx:stable-perl
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../certs/${DOMAIN_NAME}.crt:/opt/certs/${DOMAIN_NAME}.crt:ro
      - ../../certs/${DOMAIN_NAME}.key:/opt/certs/${DOMAIN_NAME}.key:ro
    ports:
      - ${LAM_NGINX_PORT}:443
    networks:
      rdl-ldap-network:
        ipv4_address: 172.20.0.26
    restart: always
  rdl-lam:
    container_name: rdl-lam
    hostname: rdl-lam
    image: ghcr.io/ldapaccountmanager/lam:stable
    environment: 
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USERS_DN=ou=people,${LDAP_BASE_DN}
      - LDAP_GROUPS_DN=ou=groups,${LDAP_BASE_DN}
      - LDAP_SERVER=ldap://rdl-ldap:389
      - LAM_LANG=ja_JP
      - LAM_PASSWORD=${LAM_PASSWORD}
      - VIRTUAL_HOST=lam
    networks:
      rdl-ldap-network:
        ipv4_address: 172.20.0.27
    restart: always
  rdl-ldap:
    container_name: rdl-ldap
    hostname: rdl-ldap
    image: osixia/openldap:1.5.0
    ports:
      - ${LDAP_PORT}:389
      - ${LDAPS_PORT}:636
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_TLS_CRT_FILENAME=${DOMAIN_NAME}.crt
      - LDAP_TLS_KEY_FILENAME=${DOMAIN_NAME}.key
      - LDAP_TLS_CA_CRT_FILENAME=${DOMAIN_NAME}.ca.crt
      - TZ=Asia/Tokyo
    volumes:
      - rdl-ldap-data:/var/lib/ldap
      - rdl-ldap-config:/etc/ldap/slapd.d
      - ../../certs/${DOMAIN_NAME}.ca.crt:/container/run/service/slapd/assets/certs/${DOMAIN_NAME}.ca.crt
      - ../../certs/${DOMAIN_NAME}.crt:/container/run/service/slapd/assets/certs/${DOMAIN_NAME}.crt
      - ../../certs/${DOMAIN_NAME}.key:/container/run/service/slapd/assets/certs/${DOMAIN_NAME}.key
    tty: true
    networks:
      rdl-ldap-network:
        ipv4_address: 172.20.0.28
    restart: always
    depends_on:
      - rdl-lam-nginx 
      - rdl-lam 
networks:
  rdl-ldap-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.24/29
        gateway: 172.20.0.25
volumes:
  rdl-ldap-data:
  rdl-ldap-config:
