services:
  rdl-sample-api-web-server:
    container_name: rdl-sample-api-web-server
    hostname: rdl-sample-api-server
    build: .
    ports:
      - ${SAMPLE_API_SERVER_PORT}:8082
    environment:
      - TZ=Asia/Tokyo
    tty: true
    user: root
    restart: always
    networks:
      rdl-sample-api-server-network:
        ipv4_address: 172.20.0.50
networks:
  rdl-sample-api-server-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.48/29
        gateway: 172.20.0.49
