FROM debian:bookworm

RUN apt-get update && apt-get -y upgrade && apt-get upgrade -y && apt-get update && apt-get install -y less vim zip git maven

RUN apt-get update && apt-get install -y ca-certificates
RUN cd /usr/share/ca-certificates && mkdir mylocal && cp -p /etc/ca-certificates.conf /etc/ca-certificates.conf.bak

COPY ./certs/__DOMAIN_NAME__.ca.crt  /certs/__DOMAIN_NAME__.ca.crt
RUN cd /usr/share/ca-certificates && cp /certs/__DOMAIN_NAME__.ca.crt mylocal/
RUN echo "mylocal/__DOMAIN_NAME__.ca.crt" >> /etc/ca-certificates.conf
RUN update-ca-certificates

RUN git clone https://github.com/keycloak-book-jp/keycloak-book-jp.git
RUN cd keycloak-book-jp/05/sample-resource-server
COPY ./application.properties /keycloak-book-jp/05/sample-resource-server/src/main/resources/application.properties

WORKDIR /keycloak-book-jp/05/sample-resource-server/
EXPOSE 8082
CMD ["mvn","spring-boot:run"]
